### PR TITLE
DF-3095 Close input streams when adding pdfs in kae

### PR DESCRIPTION
**Pull request by mdavidovski**

### CODE REVIEW

**Review by seco-mgabor — CHANGES_REQUESTED** [review]
Please provide some tests for these changes. Thank you!

**Review by emina-str — APPROVED** [review]

**Comment by mdavidovski** [comment]
> Please provide some tests for these changes. Thank you!

We need to deploy this fix in production tomorrow, which means we need it on staging for testing today (as soon as possible).
And to test such functionality (input streams and try with resources) with unit tests would take me a few hours (maybe a day).
That is why I left out the tests for now

**Comment by seco-mgabor** [comment]
> > Please provide some tests for these changes. Thank you!
> 
> We need to deploy this fix in production tomorrow, which means we need it on staging for testing today (as soon as possible).
> And to test such functionality (input streams and try with resources) with unit tests would take me a few hours (maybe a day).
> That is why I left out the tests for now

Sorry Milosh, but it's against our DoD: https://alv-ch.atlassian.net/wiki/spaces/JR2/pages/599949419/DoD+-+Definitions+of+DONE+Scrum 
It can wait another day and for that we will have better code. Please take your time and implement those tests.

**Comment by mdavidovski** [comment]
> > > Please provide some tests for these changes. Thank you!
> > 
> > 
> > We need to deploy this fix in production tomorrow, which means we need it on staging for testing today (as soon as possible).
> > And to test such functionality (input streams and try with resources) with unit tests would take me a few hours (maybe a day).
> > That is why I left out the tests for now
> 
> Sorry Milosh, but it's against our DoD: https://alv-ch.atlassian.net/wiki/spaces/JR2/pages/599949419/DoD+-+Definitions+of+DONE+Scrum
> It can wait another day and for that we will have better code. Please take your time and implement those tests.

I understand. And if it was a normal situation I would not forget the tests. However, this can be considered a hotfix for a relatively large problem in production. Are we sure that we don't want it as part of the deployment tomorrow?

**Comment by seco-mgabor** [comment]
Tests will follow, as this is very much needed in production. They must be done until 7th Nov 2020.

**Comment by mdavidovski** [comment]
> Tests will follow, as this is very much needed in production. They must be done until 7th Nov 2020.

perfect. I'll create a branch with the same ticket number. ok?

**Comment by seco-mgabor** [comment]
> > Tests will follow, as this is very much needed in production. They must be done until 7th Nov 2020.
> 
> perfect. I'll create a branch with the same ticket number. ok?

@mdavidovski please see https://alv-ch.atlassian.net/browse/DF-3123
Thank you!

**Pull request merged**
